### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Ekultek** [evyatarmeged/Raccoon#10]
```
[#] Enumerating Subdomains
[!] Trying to discover subdomains in Google
Traceback (most recent call last):
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10859a4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?q=site:bitfi.com&num=100 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10859a4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/utils/request_handler.py", line 93, in send
    return requests.get(proxies=proxies, headers=self.headers, cookies=self.cookies, *args, **kwargs)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?q=site:bitfi.com&num=100 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10859a4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 251, in <module>
    main()
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/bin/tools/Raccoon/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 230, in main
    main_loop.run_until_complete(subdomain_enumerator.run())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/lib/sub_domain.py", line 37, in run
    self._google_dork()
  File "/Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/lib/sub_domain.py", line 62, in _google_dork
    url="https://www.google.com/search?q=site:{}&num=100".format(self.target)
  File "/Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/utils/request_handler.py", line 102, in send
    raise RequestHandlerException("Error connecting to proxy")
raccoon_src.utils.exceptions.RequestHandlerException: Error connecting to proxy
Task exception was never retrieved
future: <Task finished coro=<TLSHandler.run() done, defined at /Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/lib/tls.py:204> exception=FileNotFoundError(2, "No such file or directory: 'timeout'")>
Traceback (most recent call last):
  File "/Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/lib/tls.py", line 207, in run
    self.non_sni_data = await self._execute_ssl_data_extraction()
  File "/Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/lib/tls.py", line 130, in _execute_ssl_data_extraction
    responses = await self._run_openssl_sclient_cmd(self._base_script, sni)
  File "/Users/admin/bin/tools/Raccoon/raccoon_src/../raccoon_src/lib/tls.py", line 152, in _run_openssl_sclient_cmd
    stderr=PIPE
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1516, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'timeout': 'timeout'
```

Arguments provided:
`python main.py --proxy-list proxies.txt -T 100 -t http://....com -o ...-scan --skip-health-check`

**Comment by evyatarmeged** [comment]
Mmm.. it seems your machine is having trouble running the `openssl` command with the `timeout` prefix.
What kind of system are you running this on? can you run `timeout 3 openssl s_client -connect www.google.com:443` ?

**Comment by Ekultek** [comment]
It's probably because I'm running on a mac

**Comment by Ekultek** [comment]
Also I switched to a Kali VM, and I've noticed that if a proxy provided from a proxy list fails, it will just quit and not continue the process

**Comment by evyatarmeged** [comment]
Mac timeout issue:
https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x
Seems like `timeout` is not a viable command on MacOS. 

Regarding proxies and specifically proxy lists, I know there are some issues with it and I have not yet decided how to handle request's ProxyError's (i.e, drop the failing proxy from the list after x tries, keep trying and ignore the fails, silent the error and move on, etc.)

I am open to any suggestions on this. Thanks for this issue - it is much appreciated.

**Comment by Ekultek** [comment]
No problem, I really like the tool good work. The easiest method to handle proxy issues would just be to pass to the next proxy in the list and warn the user. Thanks for the support
