### ISSUE TITLE
most recent call last Error

### ISSUE THREAD

**Issue by MrHacker46** [evyatarmeged/Raccoon#13]
Please resolve this issue.
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax

**Comment by NuclearLemon** [comment]
This tool is intended for use with Python 3 - you're running python 2.7

**Comment by evyatarmeged** [comment]
@NuclearLemon, thanks for the assistance.
@MrHacker46, please @NuclearLemon's response for the issue. This was also addressed in #4 and #5.
