### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cookies'

### ISSUE THREAD

**Issue by elig0n** [evyatarmeged/Raccoon#17]
Hello, when I invoke version 0.8.1 (from git) I get :

> Traceback (most recent call last):    
  File "./main.py", line 252, in <module> 
    main() 
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./main.py", line 159, in main
    cookies=cookies
  File "/usr/local/lib/python3.5/dist-packages/raccoon_src/utils/singleton.py", line 8, in __call__
    cls.instance = super(Singleton, cls).__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'cookies'

Installed modules: requests 2.19.1 , click 6.7 
On Python 3.5.2

**Comment by evyatarmeged** [comment]
Hi,

I think you have a collision between the source of the cloned version and pypi one. I faced a similar error when I had both installed in the same environment but when had progressed further than the other (i.e, more arguments such as `cookies` in your case).

Can you clone/pip install (one of the two, not both) to a fresh clean venv and see if it still happens?

**Comment by evyatarmeged** [comment]
Hey,

Due to lack of response I'm closing this. Feel free to open a new issue if you're still experiencing this and still require assistance.
