### ISSUE TITLE
ERROR !!!!

### ISSUE THREAD

**Issue by kali64amd** [evyatarmeged/Raccoon#20]
Hi, there

OS - Kali
python3 - Installed 

I'm clueless about this error so could anyone help me on this?
Appreciate you'r help.

ALL Requirement  has already don! 

root@shi/Desktop/Tool/Raccoon# pip3 install raccoon-scanner
Requirement already satisfied: raccoon-scanner in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from raccoon-scanner)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from raccoon-scanner)
Requirement already satisfied: fake-useragent in /usr/local/lib/python3.6/dist-packages (from raccoon-scanner)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/dist-packages (from raccoon-scanner)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from raccoon-scanner)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from raccoon-scanner)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from raccoon-scanner)

**### However still getting Error.**

841434b414c4c5448455448494e4753

https://github.com/evyatarmeged/Raccoon
-------------------------------------------------------------------
    
Error occurred during loading data. Trying to use cache server http://d2g6u4gh6d9rq0.cloudfront.net/browsers/fake_useragent_0.1.10.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 69, in get
    return response.read()
  File "/usr/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(49152 bytes read, 37746 more expected)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 69, in get
    return response.read()
  File "/usr/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(49152 bytes read, 37746 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/raccoon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/main.py", line 166, in main
    cookies=cookies
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/utils/singleton.py", line 9, in __call__
    cls.instance = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/utils/request_handler.py", line 28, in __init__
    self.headers = self._set_headers()
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/utils/request_handler.py", line 33, in _set_headers
    headers["User-Agent"] = UserAgent(verify_ssl=False).random
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/usr/local/lib/python3.6/dist-packages/fake_useragent/utils.py", line 69, in get
    return response.read()
  File "/usr/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)

**Comment by evyatarmeged** [comment]
Hi,
There is an issue with the [fake-useragent](https://github.com/hellysmile/fake-useragent) module that sometimes causes it to error for no apparent reason. The URL that is failing to be accessed (referenced in the error itself) is perfectly accessible every time I tried doing so.

The error does not seem to have a concrete affect on Raccoon's run and the scan continues normally. It does kinda suck to see an error being thrown first thing in some scans, though.

I tried catching an exception (the above said exception as well as literally trying to catch... `Exception`) on both the import statement and the object instantiation - both seem to fail and the error was still presented periodically.

I'm actually quite clueless about this. I  saw this issue on multiple other repositories who utilize the `fake-useragent` library but no actual solution presented itself (I tried, for example, setting `verify_ssl=False` on obj instantiation).

If you/anyone else has any input or work around, I would be obliged if he could share it with me. 
Thanks :snake:
