### ISSUE TITLE
Whois not found

### ISSUE THREAD

**Issue by Sydwicked** [evyatarmeged/Raccoon#30]
Help me with this issue
Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux

Task exception was never retrieved
future: <Task finished coro=<WebApplicationScanner.run_scan() done, defined at /usr/local/lib/python3.6/dist-packages/raccoon_src/lib/web_app.py:219> exception=RequestHandlerException('Connection with server timed out',)>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f810c2ae518>, 'Connection to gsrtc.in timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='gsrtc.in', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f810c2ae518>, 'Connection to gsrtc.in timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/utils/request_handler.py", line 89, in send
    return request(method, proxies=proxies, headers=self.headers, cookies=self.cookies, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='gsrtc.in', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f810c2ae518>, 'Connection to gsrtc.in timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/lib/web_app.py", line 223, in run_scan
    await self.get_web_application_info()
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/lib/web_app.py", line 201, in get_web_application_info
    self._robots()
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/lib/web_app.py", line 108, in _robots
    self.host.port
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/utils/request_handler.py", line 96, in send
    raise RequestHandlerException("Connection with server timed out")
raccoon_src.utils.exceptions.RequestHandlerException: Connection with server timed out
Task exception was never retrieved
future: <Task finished coro=<DNSHandler.grab_whois() done, defined at /usr/local/lib/python3.6/dist-packages/raccoon_src/lib/dns_handler.py:37> exception=FileNotFoundError(2, "No such file or directory: 'whois'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/lib/dns_handler.py", line 49, in grab_whois
    stderr=PIPE
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1194, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'whois': 'whois'

**Comment by purplesec** [comment]
It seems like an environment problem on your OS, check if you can do a manual whois first

If not, try running:
`apt-get install whois`

**Comment by evyatarmeged** [comment]
Hey,

Try running the above as suggested by @purplesec. After installing, try running `whois google.com` - if that works you should  be good to go.
