### ISSUE TITLE
Code execution error

### ISSUE THREAD

**Issue by Sydwicked** [evyatarmeged/Raccoon#31]
root@Firefly:~/HKIT/Raccoon# raccoon --help
Traceback (most recent call last):
  File "/usr/local/bin/raccoon", line 11, in <module>
    load_entry_point('raccoon-scanner==0.8.5', 'console_scripts', 'raccoon')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/raccoon_scanner-0.8.5-py2.7.egg/raccoon_src/main.py", line 2, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax

OS: Linux Kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux

**Comment by purplesec** [comment]
Try executing racoon with python3.

**Comment by evyatarmeged** [comment]
Sure enough, @purplesec is correct (yet again :grin:).
Closed.
