### ISSUE TITLE
scanner issue

### ISSUE THREAD

**Issue by killmasta93** [evyatarmeged/Raccoon#36]
Hi currently trying install this on kali 2020 and when i run the scanner i get this issue 

```
Traceback (most recent call last):
  File "/usr/local/bin/raccoon", line 11, in <module>
    load_entry_point('raccoon-scanner==0.8.5', 'console_scripts', 'raccoon')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/raccoon_src/main.py", line 183, in main
    host.parse()
  File "/usr/local/lib/python3.8/dist-packages/raccoon_src/lib/host.py", line 125, in parse
    self.dns_results = DNSHandler.query_dns(domains, self.dns_records)
  File "/usr/local/lib/python3.8/dist-packages/raccoon_src/lib/dns_handler.py", line 27, in query_dns
    answers = cls.resolver.query(domain, record)
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 850, in query
    rdtype = dns.rdatatype.from_text(rdtype)
  File "/usr/lib/python3/dist-packages/dns/rdatatype.py", line 212, in from_text
    raise UnknownRdatatype
dns.rdatatype.UnknownRdatatype: DNS resource record type is unknown.

```

**Comment by enoleriand-alt** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/raccoon", line 11, in <module>
    load_entry_point('raccoon-scanner==0.8.5', 'console_scripts', 'raccoon')()
