### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by Bwajajaja** [evyatarmeged/Raccoon#5]
I tried to install it using *pip install raccon-scanner but i received the following error
──╼ $pip install raccoon-scanner
Collecting raccoon-scanner
  Could not find a version that satisfies the requirement raccoon-scanner (from versions: )
No matching distribution found for raccoon-scanner
*********************************************************
Then I tried using pip3 install raccoon-scanner
I could install it, but when I try to execute it, i have this error

└──╼ $python raccoon_src/main.py
Traceback (most recent call last):
  File "raccoon_src/main.py", line 2, in <module>
    import asyncio
  File "/home/vihg02h/.local/lib/python2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/home/vihg02h/.local/lib/python2.7/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
┌─[✗]─[vihg02h@parrot]─[~/Raccoon]

************************************************************************
And when i try using python3 

──╼ $python3 raccoon_src/main.py 
Usage: main.py [OPTIONS]

Error: Missing option "-t" / "--target"
*******************************************************

I dont know what is wrong, could you help me please ?

**Comment by evyatarmeged** [comment]
Hi,

The first error is because you're using pip with python2.7 (use pip --version to validate the version).
Second error - you're trying to run main with python2.7 after installing successfully with pip3.
Third one - you are using the correct python version and actually there are no errors here. You just have to pass the -t / --target argument so Raccoon will know what to scan :) 
Use  --help for more information. 

On a side note - if you're installing from pip(3) you don't have to call `python raccoon/bla/bla`, that should be used only when you clone the repository. If a pip install is used, simply `raccoon` will suffice from the terminal (like any other cli package) as it is installed in your $PATH.
I'll update the readme to make it clearer.

**Comment by Bwajajaja** [comment]
Thanks for your help I could install it. You were right I had to do it with python3 and I would like to add it was easier using pip. But the correct sentence is pip3 install raccoon-scanner instead of pip install raccoon-scanner

**Comment by AbhiramT21** [comment]
May i know why this error coming after running raccoon installation has been completed correctly


https://github.com/evyatarmeged/Raccoon
-------------------------------------------------------------------
    
Traceback (most recent call last):
  File "/usr/local/bin/raccoon", line 33, in <module>
    sys.exit(load_entry_point('raccoon-scanner', 'console_scripts', 'raccoon')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/raccoon_scanner-0.8.5-py3.12.egg/raccoon_src/main.py", line 158, in main
    request_handler = RequestHandler(
                      ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/raccoon_scanner-0.8.5-py3.12.egg/raccoon_src/utils/singleton.py", line 9, in __call__
    cls.instance = super().__call__(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/raccoon_scanner-0.8.5-py3.12.egg/raccoon_src/utils/request_handler.py", line 28, in __init__
    self.headers = self._set_headers()
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/raccoon_scanner-0.8.5-py3.12.egg/raccoon_src/utils/request_handler.py", line 33, in _set_headers
    headers["User-Agent"] = UserAgent(verify_ssl=False).random
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'verify_ssl'
