### ISSUE TITLE
Default install errors on WAF

### ISSUE THREAD

**Issue by Skewled** [evyatarmeged/Raccoon#7]
Testing this out on a HTB machine, fresh install.

Run options: `raccoon -t 10.10.10.64 -f -o . `

### Raccoon scan finished ###
`
Task exception was never retrieved
future: <Task finished coro=<WAF.detect() done, defined at /usr/local/lib/python3.6/dist-packages/raccoon_src/lib/waf.py:138> exception=TypeError("argument of type 'NoneType' is not iterable",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/lib/waf.py", line 144, in detect
    self._detect_by_application()
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/lib/waf.py", line 130, in _detect_by_application
    result = method(response)
  File "/usr/local/lib/python3.6/dist-packages/raccoon_src/lib/waf.py", line 67, in detect_reblaze
    if "Reblaze Secure Web Gateway" in res.headers.get(SERVER) or any(
TypeError: argument of type 'NoneType' is not iterable
`

**Comment by evyatarmeged** [comment]
Thanks for pointing this out @Skewled.

I will hopefully apply a fix for it later today.

**Comment by evyatarmeged** [comment]
Fix is up. I also tested on the same machine (Stratosphere) and the scan passed.
